trigger:
  - master

stages:
  - stage: Linux
    pool:
      vmImage: 'ubuntu-18.04'
    dependsOn: []
    jobs:
      - job: "Tests"
        steps:
          - task: Gradle@2
            inputs:
              workingDirectory: ''
              gradleWrapperFile: 'gradlew'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: false
              tasks: 'clean check --stacktrace'
